package com.paraskcd.spotlightsearch.ui.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Blur: ImageVector
    get() {
        if (_Blur_on != null) return _Blur_on!!

        _Blur_on = ImageVector.Builder(
            name = "Blur_on",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 580f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(0f, -160f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(120f, 340f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(200f, 720f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(240f, 680f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(280f, 720f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(240f, 760f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(200f, 560f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(240f, 520f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(280f, 560f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(240f, 600f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(200f, 400f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(240f, 360f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(280f, 400f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(240f, 440f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(200f, 240f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(240f, 200f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(280f, 240f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(240f, 280f)
                moveToRelative(160f, 340f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(340f, 560f)
                reflectiveQuadToRelative(17.5f, -42.5f)
                reflectiveQuadTo(400f, 500f)
                reflectiveQuadToRelative(42.5f, 17.5f)
                reflectiveQuadTo(460f, 560f)
                reflectiveQuadToRelative(-17.5f, 42.5f)
                reflectiveQuadTo(400f, 620f)
                moveToRelative(0f, -160f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(340f, 400f)
                reflectiveQuadToRelative(17.5f, -42.5f)
                reflectiveQuadTo(400f, 340f)
                reflectiveQuadToRelative(42.5f, 17.5f)
                reflectiveQuadTo(460f, 400f)
                reflectiveQuadToRelative(-17.5f, 42.5f)
                reflectiveQuadTo(400f, 460f)
                moveToRelative(0f, 300f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(360f, 720f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(400f, 680f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(440f, 720f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(400f, 760f)
                moveToRelative(0f, -480f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(360f, 240f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(400f, 200f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(440f, 240f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(400f, 280f)
                moveToRelative(0f, 580f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(0f, -720f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(160f, 480f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(500f, 560f)
                reflectiveQuadToRelative(17.5f, -42.5f)
                reflectiveQuadTo(560f, 500f)
                reflectiveQuadToRelative(42.5f, 17.5f)
                reflectiveQuadTo(620f, 560f)
                reflectiveQuadToRelative(-17.5f, 42.5f)
                reflectiveQuadTo(560f, 620f)
                moveToRelative(0f, -160f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(500f, 400f)
                reflectiveQuadToRelative(17.5f, -42.5f)
                reflectiveQuadTo(560f, 340f)
                reflectiveQuadToRelative(42.5f, 17.5f)
                reflectiveQuadTo(620f, 400f)
                reflectiveQuadToRelative(-17.5f, 42.5f)
                reflectiveQuadTo(560f, 460f)
                moveToRelative(0f, 300f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(520f, 720f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(560f, 680f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(600f, 720f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(560f, 760f)
                moveToRelative(0f, -480f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(520f, 240f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(560f, 200f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(600f, 240f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(560f, 280f)
                moveToRelative(0f, 580f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(0f, -720f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(160f, 620f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(680f, 720f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(720f, 680f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(760f, 720f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(720f, 760f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(680f, 560f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(720f, 520f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(760f, 560f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(720f, 600f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(680f, 400f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(720f, 360f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(760f, 400f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(720f, 440f)
                moveToRelative(0f, -160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(680f, 240f)
                reflectiveQuadToRelative(11.5f, -28.5f)
                reflectiveQuadTo(720f, 200f)
                reflectiveQuadToRelative(28.5f, 11.5f)
                reflectiveQuadTo(760f, 240f)
                reflectiveQuadToRelative(-11.5f, 28.5f)
                reflectiveQuadTo(720f, 280f)
                moveToRelative(120f, 300f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                moveToRelative(0f, -160f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                reflectiveQuadToRelative(-6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
            }
        }.build()

        return _Blur_on!!
    }

private var _Blur_on: ImageVector? = null